### ISSUE TITLE
way to acknowledge alert?

### ISSUE THREAD

**Issue by jboisdequin** [multiversx/mx-chain-keys-monitor-go#26]
Hi, I've been using this tool in addition of our current Mx monitoring.
We get alerts on a telegram channel.

We just add a node to our SP that comes from inactive (with previously rating 100) to aunction status.
The script detects a Rating drop detected from 100 to 50, which is normal.

The issue is we get spammed from it every 5minutes for something we know and where we don't need to intervene.
Is there a way to stop sending notifications after the first one?

**Comment by iulianpascalau** [comment]
Hello. Very good point. I will think about adding a new parameter: a "snooze" variable, like set to 3 indicating the number of consecutive alerts the app will be sending before it will mute them for a period of time, like 24h

**Comment by iulianpascalau** [comment]
Done. Hope the solution works for you.
